/* Données de référence du système solaire, partagées par le mode classique et le récit.
   period = année terrienne · dayH = heures (négatif = rotation rétrograde)
   tilt = inclinaison axiale · incl = inclinaison orbitale
   moons: r = rayon relatif · d = distance orbitale relative · c = teinte · s = vitesse */
export const SUN_DIAMETER = 1392700

export const planets = [
  {
    id: 'mercury', name: 'Mercure', type: 'Tellurique',
    diameter: 4879, distance: 0.39, color: 0x9b9da4, accent: '#bfc4cb',
    mass: '3,30 × 10²³ kg', gravity: '3,7 m/s²', orbitalPeriod: '88 jours',
    dayLength: '58,6 jours', temperature: '-180 °C à 430 °C',
    period: 0.241, dayH: 1407.6, tilt: 0.03, incl: 7.0,
    moons: [],
    description: 'Le plus petit monde et le plus proche du Soleil. Sa surface cratérisée connaît des écarts thermiques extrêmes entre le jour et la nuit.',
    myth: 'Mercure porte le nom du messager ailé des dieux romains, aussi rapide dans le ciel que le dieu l’était sur terre : c’est la planète qui boucle son orbite le plus vite, en à peine 88 jours.',
    story: 'Longtemps crue bloquée en rotation synchrone comme notre Lune, elle n’a révélé sa vraie période de rotation qu’en 1965, grâce à un radar californien — avant d’être cartographiée de près par les sondes Mariner 10 puis MESSENGER.',
    wow: 'Un jour mercurien (d’un lever de Soleil à l’autre) dure deux années mercuriennes : à cause d’une rotation lente et d’une orbite rapide, le Soleil y semble se lever, reculer un instant, puis se lever à nouveau.',
  },
  {
    id: 'venus', name: 'Vénus', type: 'Tellurique',
    diameter: 12104, distance: 0.72, color: 0xd5a35f, accent: '#f4d6a0',
    mass: '4,87 × 10²⁴ kg', gravity: '8,87 m/s²', orbitalPeriod: '225 jours',
    dayLength: '243 jours', temperature: '462 °C (surface)',
    period: 0.615, dayH: -5832.5, tilt: 177.4, incl: 3.39,
    moons: [],
    description: 'Une planète jumelle de la Terre par sa taille, mais enveloppée d’une atmosphère dense et brûlante à base de CO₂ qui piège la chaleur.',
    myth: 'Vénus doit son nom à la déesse romaine de l’amour et de la beauté, en hommage à l’éclat qui en fait l’astre le plus brillant du ciel nocturne après la Lune.',
    story: 'En 1982, la sonde soviétique Venera 13 y a posé la première caméra couleur à avoir photographié le sol d’une autre planète — avant d’être écrasée par la chaleur et la pression en un peu plus de deux heures.',
    wow: 'Vénus tourne sur elle-même à l’envers de presque toutes les autres planètes, si lentement qu’une journée vénusienne dure plus longtemps qu’une année vénusienne.',
  },
  {
    id: 'earth', name: 'Terre', type: 'Tellurique',
    diameter: 12756, distance: 1, color: 0x277bb7, accent: '#8fc8d3',
    mass: '5,97 × 10²⁴ kg', gravity: '9,8 m/s²', orbitalPeriod: '365,25 jours',
    dayLength: '23 h 56 min', temperature: '15 °C (moyenne)',
    period: 1, dayH: 23.93, tilt: 23.44, incl: 0,
    moons: [{ name: 'Lune', r: 0.27, d: 2.7, c: 0xcfcfcf, s: 1.0 }],
    description: 'Notre planète océan, seule planète connue à abriter une biosphère riche et diversifiée. Une lune unique et massive stabilise son axe.',
    myth: 'Seule planète du système à ne pas porter le nom d’une divinité gréco-romaine, la Terre tire le sien d’un vieux mot germanique désignant simplement le sol — celui sur lequel on se tient.',
    story: 'Vue pour la première fois se lever au-dessus de l’horizon lunaire par l’équipage d’Apollo 8 en 1968, la photo « Lever de Terre » a changé la façon dont l’humanité se percevait : une bille bleue fragile, suspendue dans le noir.',
    wow: 'La Lune s’éloigne de nous d’environ 3,8 cm par an — à peu près la vitesse à laquelle poussent les ongles.',
  },
  {
    id: 'mars', name: 'Mars', type: 'Tellurique',
    diameter: 6792, distance: 1.52, color: 0xb55e45, accent: '#e9a57f',
    mass: '6,42 × 10²³ kg', gravity: '3,71 m/s²', orbitalPeriod: '687 jours',
    dayLength: '24 h 37 min', temperature: '-63 °C (moyenne)',
    period: 1.881, dayH: 24.62, tilt: 25.19, incl: 1.85,
    moons: [
      { name: 'Phobos', r: 0.08, d: 1.8, c: 0xb0a494, s: 2.8 },
      { name: 'Déimos', r: 0.06, d: 2.5, c: 0xa89c8c, s: 2.1 },
    ],
    description: 'Le désert rouge conserve les traces d’une histoire géologique et hydrologique fascinante. Ses deux lunes sont de petits astéroïdes capturés.',
    myth: 'Mars porte le nom du dieu romain de la guerre, sans doute à cause de sa teinte rouge sang : l’oxyde de fer qui recouvre sa surface est la même rouille qui colore le nôtre.',
    story: 'Depuis 1997, chaque rover posé sur Mars a dépassé la durée de mission prévue — Opportunity, conçu pour tenir 90 jours, a fonctionné pendant près de 15 ans.',
    wow: 'Mars porte Olympus Mons, le plus grand volcan connu du système solaire : environ trois fois la hauteur de l’Everest, et large comme la France.',
  },
  {
    id: 'jupiter', name: 'Jupiter', type: 'Géante gazeuse',
    diameter: 142984, distance: 5.2, color: 0xbc906a, accent: '#f3d7b0',
    mass: '1,90 × 10²⁷ kg', gravity: '24,79 m/s²', orbitalPeriod: '11,86 ans',
    dayLength: '9 h 55 min', temperature: '-108 °C (nuages)',
    period: 11.86, dayH: 9.93, tilt: 3.13, incl: 1.3,
    moons: [
      { name: 'Io', r: 0.26, d: 1.9, c: 0xd8c27a, s: 2.2 },
      { name: 'Europe', r: 0.22, d: 2.45, c: 0xd8cdbb, s: 1.7 },
      { name: 'Ganymède', r: 0.34, d: 3.05, c: 0xa89a8a, s: 1.3 },
      { name: 'Callisto', r: 0.3, d: 3.7, c: 0x8d8378, s: 1.0 },
    ],
    description: 'Le géant du système solaire. Ses quatre lunes galiléennes forment un mini-système fascinant. La Grande Tache Rouge est une tempête géante.',
    myth: 'Jupiter porte le nom du roi des dieux romains, à la mesure de son titre de plus grosse planète du système : on pourrait y loger plus de 1300 Terres.',
    story: 'En 1610, Galilée y observe quatre points lumineux qui changent de position nuit après nuit : les lunes Io, Europe, Ganymède et Callisto — première preuve que tous les astres ne tournent pas autour de la Terre.',
    wow: 'La Grande Tache Rouge, une tempête plus large que la Terre entière, est observée sans interruption depuis au moins 1830.',
  },
  {
    id: 'saturn', name: 'Saturne', type: 'Géante gazeuse',
    diameter: 120536, distance: 9.54, color: 0xd0b47b, accent: '#f1dbad',
    mass: '5,68 × 10²⁶ kg', gravity: '10,44 m/s²', orbitalPeriod: '29,46 ans',
    dayLength: '10 h 33 min', temperature: '-139 °C (nuages)',
    period: 29.46, dayH: 10.66, tilt: 26.73, incl: 2.49,
    moons: [
      { name: 'Encelade', r: 0.1, d: 2.7, c: 0xe8ecec, s: 1.6 },
      { name: 'Dioné', r: 0.13, d: 3.1, c: 0xcfcbc0, s: 1.4 },
      { name: 'Rhéa', r: 0.12, d: 3.5, c: 0xc5c0b5, s: 1.2 },
      { name: 'Titan', r: 0.3, d: 4.1, c: 0xc8a25f, s: 0.95 },
      { name: 'Japet', r: 0.13, d: 4.8, c: 0xb0a898, s: 0.7 },
    ],
    description: 'Un monde pâle entouré d’anneaux glacés spectaculaires et d’une famille de lunes remarquables. Titan possède une atmosphère dense.',
    myth: 'Saturne, dieu romain du temps et des moissons — et père de Jupiter dans la mythologie —, prête son nom à la planète la plus lente à se déplacer dans le ciel à l’œil nu : 29 ans pour un tour complet.',
    story: 'La sonde Cassini a passé treize ans en orbite autour de Saturne avant de plonger volontairement dans son atmosphère en 2017, pour ne jamais risquer de contaminer les lunes Encelade ou Titan, jugées propices à la vie.',
    wow: 'Saturne est si peu dense qu’elle flotterait sur l’eau — s’il existait un océan assez grand pour l’accueillir.',
  },
  {
    id: 'uranus', name: 'Uranus', type: 'Géante de glace',
    diameter: 51118, distance: 19.19, color: 0x77b8c0, accent: '#c3f0ec',
    mass: '8,68 × 10²⁵ kg', gravity: '8,69 m/s²', orbitalPeriod: '84 ans',
    dayLength: '17 h 14 min', temperature: '-197 °C (nuages)',
    period: 84.02, dayH: -17.24, tilt: 97.77, incl: 0.77,
    moons: [
      { name: 'Miranda', r: 0.09, d: 2.2, c: 0xb8c4c4, s: 1.5 },
      { name: 'Ariel', r: 0.13, d: 2.6, c: 0xc4cccc, s: 1.3 },
      { name: 'Umbriel', r: 0.12, d: 3.0, c: 0x9ca8a8, s: 1.1 },
      { name: 'Titania', r: 0.15, d: 3.5, c: 0xbcc4c4, s: 0.9 },
      { name: 'Obéron', r: 0.15, d: 4.0, c: 0xb4bec0, s: 0.75 },
    ],
    description: 'Une géante bleu-vert qui tourne presque sur le côté (inclinaison de 98°), avec un système d’anneaux discrets et une famille de lunes glacées.',
    myth: 'Seule planète nommée d’après une divinité grecque plutôt que romaine, Uranus (le Ciel primordial) est aussi le seul astre du système dont l’axe est couché : elle roule presque sur le flanc autour du Soleil.',
    story: 'Découverte par William Herschel en 1781, elle a d’abord été prise pour une comète, puis pour une étoile, avant qu’on ne comprenne qu’il s’agissait d’une planète — la première trouvée au télescope, et non à l’œil nu.',
    wow: 'À cause de son inclinaison de 98°, chaque pôle d’Uranus connaît 42 années de jour continu, suivies de 42 années de nuit continue.',
  },
  {
    id: 'neptune', name: 'Neptune', type: 'Géante de glace',
    diameter: 49528, distance: 30.07, color: 0x3d63b5, accent: '#9eb8ff',
    mass: '1,02 × 10²⁶ kg', gravity: '11,15 m/s²', orbitalPeriod: '164,8 ans',
    dayLength: '16 h 6 min', temperature: '-201 °C (nuages)',
    period: 164.8, dayH: 16.11, tilt: 28.32, incl: 1.77,
    moons: [
      { name: 'Protée', r: 0.12, d: 2.1, c: 0x9aa4a8, s: 1.3 },
      { name: 'Triton', r: 0.22, d: 2.7, c: 0xd0d8dc, s: -1.2 },
      { name: 'Néréide', r: 0.07, d: 3.6, c: 0xa8a094, s: 0.6 },
    ],
    description: 'La frontière bleue du système solaire, balayée par des vents supersoniques les plus rapides du système. Triton orbite à rebours.',
    myth: 'Neptune, dieu romain des mers, doit son bleu profond au méthane de son atmosphère, qui absorbe la lumière rouge du Soleil.',
    story: 'Neptune est la seule planète découverte par le calcul avant d’être vue : en 1846, les perturbations de l’orbite d’Uranus ont permis de prédire sa position, et on l’a trouvée au télescope la nuit même.',
    wow: 'Une année sur Neptune dure 165 années terrestres : elle n’a bouclé sa première orbite complète depuis sa découverte qu’en 2011.',
  },
]

/* Le Soleil n'est pas une planète : pas d'orbite, pas de lune, mais la même
   fiche d'observation lui est ouverte au clic sur son étiquette — il est,
   après tout, le personnage principal de toute cette histoire. */
export const sunInfo = {
  id: 'sun', name: 'Soleil', type: 'Étoile — naine jaune, type G2V',
  diameter: SUN_DIAMETER, distance: 0, color: 0xffcf7a, accent: '#ffdca0',
  mass: '1,989 × 10³⁰ kg (99,86 % de la masse du système)', gravity: '274 m/s² (surface)',
  orbitalPeriod: '≈ 225 millions d’années (autour du centre de la galaxie)',
  dayLength: '≈ 27 jours (rotation équatoriale)', temperature: '5 500 °C (surface) — 15 000 000 °C (cœur)',
  moons: [],
  description: 'Une boule de plasma en fusion permanente, assez massive pour courber l’espace autour d’elle et maintenir huit planètes en orbite depuis 4,6 milliards d’années.',
  myth: 'Sol, le dieu-Soleil romain, prête son nom à notre étoile — mais c’est le grec hêlios qui a donné « héliocentrique », le mot qui a mis fin à des siècles de certitude que la Terre était le centre de tout.',
  story: 'En 1919, une éclipse totale a permis à des astronomes britanniques de mesurer comment le Soleil dévie la lumière des étoiles lointaines — confirmant la relativité générale d’Einstein, et le rendant célèbre du jour au lendemain.',
  wow: 'Le Soleil représente 99,86 % de la masse totale du système solaire : tout le reste — huit planètes, leurs lunes, les astéroïdes — tient dans les 0,14 % restants.',
}
